### ISSUE TITLE
Restructure developers config & its validation to allow for easier expansion of settings

### ISSUE THREAD

**Issue by dawalters1** [dawalters1/wolf.js#146]
Version 1 (Current & Default Settings) 
```yaml
keyword: default # SINGLE word only. EX: tag, battlestars, manager, dua, notes
app:
  defaultLanguage: en
  developerId: undefined # Your ID should go here
  commandSettings:
    ignoreOfficialBots: true
    ignoreUnofficialBots: false
  messageSettings:
    subscriptions: # Optional, All TRUE by Default
      groupTipping: false # Prevent the bot from receiving group tip events
      groupMessages: true # Prevent the bot from receiving group message events
      privateMessages: true # Prevent the bot from receiving private message events
```

Version 2 (New  & Default Settings)
```yaml
keyword: default
framework:  #all settings relating to wolf.js
  developer: undefined # Bypasses all group member capability checks 
  language: en # default response language
  login: 
    email: undefined
    password: undefined
    onlineState: 1
  command: # command settings
    ignore: 
      official: false # whether or not an official bot will trigger a command (internal)
      unofficial: false  # whether or not an unofficial bot will trigger a command (internal)
      self: true  # whether or not the bot will process its own messages and trigger its own commands (internal)
  message: # message settings
    ignore:
      self: true # whether or not the bot will process its own messages (internal)
  subscriptions: # subscription settings
    messages: # message subscriptions
      group:
        enabled: true #subscribe to group messages  (server)
        tipping: true # subscribe to group message tip events  (server)
      private:
        enabled: true # subscribe to private messages (server)
        tipping: false  # subscribe to private message tip events  (server) - NOT IMPLEMENTED 
```
